yatube/about/urls.py
# файл about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
# после ключевого слова в url переход на какие обработчики
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    # Главная страница
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
# Профайл пользователя
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:id_post>/edit/', views.post_edit, name='post_edit')
]

yatube/yatube/urls.py
# главные слова в url адресах после которых переходим в приложение

"""
URL configuration for yatube project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Дорогой Джанго, если запрошена главная страница (''),
    # перейди в файл urls приложения ice_cream и проверь там все пути
    path('', include('posts.urls', namespace='posts')),
    # Встроенная админка в Django подключена по этому адресу «из коробки»
    path('admin/', admin.site.urls),
    # Все адреса с префиксом /auth
    # будут прернаправлены в модуль django.contrib.auth
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

# обработчик страницы с ошибкой, для 403 - в settings.py
handler404 = 'core.views.page_not_found'

#При дефолтных настройках проекта в режиме
# разработчика Django не будет раздавать картинки,
# загруженные пользователями, настроим отображение:
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
# создание моделей в бд

from django.db import models


from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.TextField()
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField('Введите текст статьи', help_text='Введите текст поста')
    pub_date = models.DateTimeField('Дата публикации',auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор'
    )
    # Post.objects.filter(text__contains='утро').filter(author='leo').filter(pub_date__range
    group = models.ForeignKey(
        Group,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Выберете группу',
        help_text='Выберите группу'
    )
    # Поле для картинки (необязательное)
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    # Аргумент upload_to указывает директорию,
    # в которую будут загружаться пользовательские файлы.

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]

yatube/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:

        # На основе какой модели создаётся класс формы
        model = Post
        # Укажем, какие поля будут в форме
        fields = ('text', 'group', 'image')

        # Метод-валидатор для поля text
    def clean_subject(self):
        text = self.cleaned_data['text']

            # Если пользователь не поблагодарил администратора - считаем это ошибкой
        if text == '':
            raise forms.ValidationError('Вы обязательно должны заполнить это поле')

            # Метод-валидатор обязательно должен вернуть очищенные данные,
            # даже если не изменил их
        return text

yatube/posts/views.py
# обработчики url адресов

import datetime
from django.core.paginator import Paginator
from django.shortcuts import render

from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404

from django.http import HttpResponse

from .forms import PostForm
from .models import Post, Group

from django.shortcuts import redirect


#декоратор который проверяет зарегистрирован ли пользователь
def authorized_only(func):
    # Функция-обёртка в декораторе может быть названа как угодно
    def check_user(request, *args, **kwargs):
        # В любую view-функции первым аргументом передаётся объект request,
        # в котором есть булева переменная is_authenticated,
        # определяющая, авторизован ли пользователь.
        if request.user.is_authenticated:
            # Возвращает view-функцию, если пользователь авторизован.
            return func(request, *args, **kwargs)
        # Если пользователь не авторизован — отправим его на страницу логина.
        return redirect('/auth/login/')
    return check_user


# Главная страница
#@authorized_only
def index(request):
    # Одна строка вместо тысячи слов на SQL:
    # в переменную posts будет сохранена выборка из 10 объектов модели Post,
    # отсортированных по полю pub_date по убыванию (от больших значений к меньшим)
    keyword = "утро"
    start_date = datetime.date(1854, 7, 7)
    end_date = datetime.date(1854, 7, 21)
    posts = Post.objects.filter(text__contains=keyword).filter(
        pub_date__range=(start_date, end_date))
    # В словаре context отправляем информацию в шаблон
    context = {
        'posts': posts,
        'title': 'Последние обновления на сайте',
        'keyword': keyword
    }
    #работа с паджинатором
    post_list = Post.objects.all().order_by('-pub_date')
    # Если порядок сортировки определен в классе Meta модели,
    # запрос будет выглядить так:
    # post_list = Post.objects.all()
    # Показывать по 10 записей на странице.
    paginator = Paginator(post_list, 10)

    # Из URL извлекаем номер запрошенной страницы - это значение параметра page
    page_number = request.GET.get('page')

    # Получаем набор записей для страницы с запрошенным номером
    page_obj = paginator.get_page(page_number)
    # Отдаем в словаре контекста
    context = {
        'page_obj': page_obj,
        'title': 'Последние обновления на сайте',
    }

    return render(request, 'posts/index.html', context)


# View-функция для страницы сообщества:
def group_posts(request, slug):
    # Функция get_object_or_404 получает по заданным критериям объект
    # из базы данных или возвращает сообщение об ошибке, если объект не найден.
    # В нашем случае в переменную group будут переданы объекты модели Group,
    # поле slug у которых соответствует значению slug в запросе

    #group = get_object_or_404(Group, slug=slug)

    # Метод .filter позволяет ограничить поиск по критериям.
    # Это аналог добавления
    # условия WHERE group_id = {group_id}
    # posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    # context = {
    #     'group': group,
    #     'posts': posts,
    #     'title': f'Записи сообщества {group}',
    # }

    group = get_object_or_404(Group, slug=slug)
    post_list = Post.objects.all().filter(group=group).order_by('-pub_date')
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'title': f'Записи сообщества {group}',
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = User.objects.get(username=username)
    # Здесь код запроса к модели и создание словаря контекста
    post_list = Post.objects.all().filter(author=author).order_by('-pub_date')
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'title': f'профайл пользователя {username}',
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    #post = get_object_or_404(Post, id=post_id)
    post = Post.objects.filter(id=post_id)
    context = {
        'post': post
    }
    return render(request, 'posts/post_detail.html', context)


def post_create(request):

    if request.method == 'POST':
        form = PostForm(
            request.POST or None,
            files=request.FILES or None,
        )
        if form.is_valid():
            post = form.save(False)
            post.author = request.user
            post.save()
            return redirect(f'/profile/{request.user.username}/')
        return render(request, 'posts/create_post.html', {'form': form, 'is_edit': False})
    form = PostForm()
    return render(request, 'posts/create_post.html', {'form': form, 'is_edit': False})


def post_edit(request, id_post):
    post = get_object_or_404(Post, pk=id_post)

    if request.method == 'POST':
        form = PostForm(
            request.POST or None,
            files=request.FILES or None,
            instance=post
        )

        #if post.author != request.user:
        # return redirect('posts:post_detail', post_id=id_post)

        if form.is_valid():
            form.save()
            return redirect(f'/profile/{request.user.username}/')

        return render(request, 'posts/create_post.html', {'form': form, 'is_edit': True, 'post': post})

    form = PostForm(instance=post)


    return render(request, 'posts/create_post.html', {'form': form, 'is_edit': True, 'post': post, 'name': post.text})

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
<title>{% if is_edit %}
  Редактироввать пост
{% else %}
  Добавить пост
  {% endif %}
</title>
{% endblock %}
{% block content %}
{% load thumbnail %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
  Редактироввать пост
{% else %}
  Добавить пост
  {% endif %}
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}
          <form
            {% if is_edit %}
            method="post" enctype="multipart/form-data" action="{% url 'posts:post_edit' post.id %}"
            {% else %}
            method="post" enctype="multipart/form-data" action="{% url 'posts:post_create' %}"
            {% endif %}>
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %}
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
            {% if is_edit %}
                Сохранить
            {% else %}
              Добавить
            {% endif %}
              </button>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
<title>{{title}}</title>
{% endblock %}
{% block content %}
{% load thumbnail %}
<!-- класс py-5 создает отступы сверху и снизу блока -->
<div class="container py-5">
    <h1>Записи сообщества: {{group.title}}</h1>
    {% for post in page_obj %}
  <ul>
    <li>
      Автор: <a href="{% url 'posts:profile' post.author.username %}">{{post.author.username}}</a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text|truncatechars:30 }}</p>
   <!-- отображаем картинки -->
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
  <p><a href="{% url 'posts:post_detail' post.id %}">Подробнее о посте</a></p>
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
<title>{{title}}</title>
{% endblock %}
{% block content %}
{% load thumbnail %}
<div class="container py-5">
    {% for post in page_obj %}
  <ul>
    <li>
      Автор: <a href="{% url 'posts:profile' post.author.username %}">{{post.author.username}}</a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
    {% if post.group %}
    <li>
      Группа: {{ post.group.title }}
    </li>
    {% endif %}
  </ul>
  <p>{{ post.text|truncatechars:30 }}</p>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
  {% if post.group %}
  <a href="{% url 'posts:group_posts' post.group.slug %}">Все записи группы</a>
{% endif %}
  <p></p>
  {% if post.author.id == user.id %}
  <a href="{% url 'posts:post_edit' post.id  %}">Редактировать</a>
  {% else %}
  <a href="{% url 'posts:post_detail' post.id %}">Подробнее о посте</a>
  {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
    <!-- Подключены иконки, стили и заполенены мета теги -->
     <title>Пост {{post.0.id}}</title>
{% endblock %}
{% block content %}
{% load thumbnail %}
      <div class="container py-5">
        <article>
  <ul>
    <li>
      Автор: {{ post.0.author.username }}
    </li>
    <li>
      Дата публикации: {{ post.0.pub_date|date:"d E Y" }}
    </li>
    <li>
      Группа: {{ post.0.group.title }}
    </li>
  </ul>
          <p>
            {{ post.0.text }}
          </p>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            {% thumbnail post.0.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
        </article>
          {% if post.0.group %}
            <a href="{% url 'posts:group_posts' post.0.group.slug %}">Все записи группы</a>
        {% endif %}
        <hr>
        {% include 'posts/includes/paginator.html' %}
</div>
{% endblock%}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
    <!-- Подключены иконки, стили и заполенены мета теги -->
    <title>{{title}}</title>
{% endblock %}
{% block content %}
      <div class="container py-5">
        <h1>Все посты пользователя {{page_obj.0.author.username}} </h1>
        <h3>Всего постов: {{page_obj|length }}</h3>
        <article>
          {% for post in page_obj %}
  <ul>
    <li>
      Автор: <a href="{% url 'posts:profile' post.author.username %}">{{post.author.username}}</a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
          <p>
            {{ post.text|truncatechars:30 }}
          </p>
        </article>
          {% if post.author.id == user.id %}
  <a href="{% url 'posts:post_edit' post.id  %}">Редактировать</a>
  {% else %}
  <a href="{% url 'posts:post_detail' post.id %}">Подробнее о посте</a>
  {% endif %}
          <p></p>
          {% if post.0.group %}
            <a href="{% url 'posts:group_posts' post.group.slug %}">Все записи группы</a>
        {% endif %}
        <hr>
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/update_post.html
<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="../img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="../img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="../css/bootstrap.min.css">
    <title>Редактировать пост</title>
  </head>
  <body>	   
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="../posts/index.html">
            <img src="../img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>        
          <ul class="nav  nav-pills">
            <li class="nav-item">              
              <a class="nav-link" href="../about/author.html">
                Об авторе
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="../about/tech.html">
                Технологии
              </a>
            </li>
            <!-- пункты меню видны только авторизованному пользователю -->
            <li class="nav-item">
              <a class="nav-link active" href="../posts/create_post.html">
                Новая запись
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light " href="../users/password_change_form.html">
                Изменить пароль
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light" href="../users/logged_out.html">Выйти</a>
            </li>
            <li>
              Пользователь: leo
            <li>
            <!-- конец пункты меню видны только авторизованному пользователю -->
            <!-- пункты меню видны только неавторизованному пользователю -->
            <li class="nav-item"> 
              <a class="nav-link link-light" href="../users/login.html">
                Войти
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light " href="../users/signup.html">Регистрация</a>
            </li>
            <!-- конец пункты меню видны только неавторизованному пользователю -->        
          </ul>      
        </div>
      </nav> 
    </header>
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                Редактировать пост             
              </div>
              <div class="card-body">        
                <form method="post" action="../posts/create_post.html">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">            
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста                  
                      <span class="required text-danger" >*</span>                  
                    </label>
                    <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">[Фокшаны.] Еще переходъ до Фокшанъ, во время котораго я ѣхалъ съ Монго. Человѣкъ пустой, но съ твердыми, хотя и ложными убѣжденіями. Генерал[у] по этому должно быть случаю, угодно было спрашивать о моемъ здоровьи. Свинья! К[о]вырялъ носъ и ничего не написалъ — вотъ 2 упрека за нын[ѣшній] день. Послѣдній упрекъ становится слишкомъ частъ, хотя походъ и можетъ служить въ немъ отчасти извиненіемъ. Отношенія мои съ товарищами становятся такъ пріятны, что мнѣ жалко бросить штабъ. Здоровье кажется (2) лучше.
                    </textarea>                
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>                  
                  </div>            
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Group                  
                    </label>
                    <select name="group" class="form-control" id="id_group">
                      <option value="">---------</option>
                      <option value="1" selected>Группа: Лев Толстой – зеркало русской революции</option>
                    </select>
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      Добавить
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
    <footer class="border-top text-center py-3">
      <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>    
    </footer>
  </body>
</html>